// Mocks generated by Mockito 5.4.6 from annotations
// in ooh_mobile/test/features/discover/presentation/blocs/discover_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:ooh_mobile/core/utils/result.dart' as _i4;
import 'package:ooh_mobile/features/discover/data/api/api.dart' as _i9;
import 'package:ooh_mobile/features/discover/data/dto/dto.dart' as _i10;
import 'package:ooh_mobile/features/discover/data/repository/discover_repository.dart'
    as _i2;
import 'package:ooh_mobile/features/discover/domain/entities/city.dart' as _i7;
import 'package:ooh_mobile/features/discover/domain/entities/country.dart'
    as _i5;
import 'package:ooh_mobile/features/discover/domain/entities/ooh_unit.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DiscoverRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoverRepository extends _i1.Mock
    implements _i2.DiscoverRepository {
  @override
  _i3.Future<_i4.Result<List<_i5.Country>>> getCountries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCountries,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.Country>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.Country>>>(
          this,
          Invocation.method(
            #getCountries,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<List<_i5.Country>>>.value(
                _i6.dummyValue<_i4.Result<List<_i5.Country>>>(
          this,
          Invocation.method(
            #getCountries,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.Country>>>);

  @override
  _i3.Future<_i4.Result<List<_i7.City>>> getCities({int? countryId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCities,
          [],
          {#countryId: countryId},
        ),
        returnValue: _i3.Future<_i4.Result<List<_i7.City>>>.value(
            _i6.dummyValue<_i4.Result<List<_i7.City>>>(
          this,
          Invocation.method(
            #getCities,
            [],
            {#countryId: countryId},
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i4.Result<List<_i7.City>>>.value(
            _i6.dummyValue<_i4.Result<List<_i7.City>>>(
          this,
          Invocation.method(
            #getCities,
            [],
            {#countryId: countryId},
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i7.City>>>);

  @override
  _i3.Future<_i4.Result<List<_i8.OohUnit>>> getUnits(
          {_i9.InventoryFilterParams? filters}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnits,
          [],
          {#filters: filters},
        ),
        returnValue: _i3.Future<_i4.Result<List<_i8.OohUnit>>>.value(
            _i6.dummyValue<_i4.Result<List<_i8.OohUnit>>>(
          this,
          Invocation.method(
            #getUnits,
            [],
            {#filters: filters},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<List<_i8.OohUnit>>>.value(
                _i6.dummyValue<_i4.Result<List<_i8.OohUnit>>>(
          this,
          Invocation.method(
            #getUnits,
            [],
            {#filters: filters},
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i8.OohUnit>>>);

  @override
  _i3.Future<_i4.Result<_i8.OohUnit>> getUnitById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnitById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Result<_i8.OohUnit>>.value(
            _i6.dummyValue<_i4.Result<_i8.OohUnit>>(
          this,
          Invocation.method(
            #getUnitById,
            [id],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i4.Result<_i8.OohUnit>>.value(
            _i6.dummyValue<_i4.Result<_i8.OohUnit>>(
          this,
          Invocation.method(
            #getUnitById,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i8.OohUnit>>);

  @override
  _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>> getUnitTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnitTypes,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>>.value(
            _i6.dummyValue<_i4.Result<List<_i10.DictionaryRefDto>>>(
          this,
          Invocation.method(
            #getUnitTypes,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>>.value(
                _i6.dummyValue<_i4.Result<List<_i10.DictionaryRefDto>>>(
          this,
          Invocation.method(
            #getUnitTypes,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>>);

  @override
  _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>> getMediaFormats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaFormats,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>>.value(
            _i6.dummyValue<_i4.Result<List<_i10.DictionaryRefDto>>>(
          this,
          Invocation.method(
            #getMediaFormats,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>>.value(
                _i6.dummyValue<_i4.Result<List<_i10.DictionaryRefDto>>>(
          this,
          Invocation.method(
            #getMediaFormats,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>>);

  @override
  _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>> getVenueTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getVenueTypes,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>>.value(
            _i6.dummyValue<_i4.Result<List<_i10.DictionaryRefDto>>>(
          this,
          Invocation.method(
            #getVenueTypes,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>>.value(
                _i6.dummyValue<_i4.Result<List<_i10.DictionaryRefDto>>>(
          this,
          Invocation.method(
            #getVenueTypes,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i10.DictionaryRefDto>>>);
}
